// components/sections/Footer.tsx
import {
  Mail,
  Clock,
  Globe,
  Youtube,
  Twitch,
  Twitter,
  ShieldCheck,
  Heart,
  Shield,
  Phone,
  MapPin,
  ExternalLink
} from 'lucide-react';

export function Footer() {
  return (
    <footer className="footer py-16 relative overflow-hidden">
      {/* Background Elements */}
      <div className="absolute inset-0 bg-gradient-to-br from-gray-900/50 via-black/50 to-gray-900/50"></div>
      <div className="absolute top-0 left-0 w-96 h-96 bg-blue-500/5 rounded-full blur-3xl"></div>
      <div className="absolute bottom-0 right-0 w-80 h-80 bg-purple-500/5 rounded-full blur-3xl"></div>

      <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* Main Footer Content */}
        <div className="text-center mb-12">
          {/* Company Info */}
          <div className="flex items-center justify-center mb-8">
            <div className="w-16 h-16 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center mr-4">
              <Shield className="w-8 h-8 text-white" />
            </div>
            <h3 className="text-3xl font-bold text-white">RescuePC Repairs</h3>
          </div>

          <p className="text-white/80 mb-8 leading-relaxed max-w-2xl mx-auto text-lg">
            Professional Windows repair toolkit with military-grade security. Lifetime license, 24/7
            support, and offline operation for maximum privacy and performance.
          </p>

          <div className="flex items-center justify-center space-x-8 mb-8">
            <div className="flex items-center text-white/60">
              <Mail className="w-5 h-5 mr-2" />
              <span className="text-sm">rescuepcrepair@yahoo.com</span>
            </div>
            <div className="flex items-center text-white/60">
              <Clock className="w-5 h-5 mr-2" />
              <span className="text-sm">24/7 Support</span>
            </div>
          </div>
        </div>

        {/* Navigation Links */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
          {/* Product */}
          <div className="text-center">
            <h4 className="text-lg font-semibold text-white mb-6">Product</h4>
            <ul className="space-y-3">
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  Features
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  Pricing
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  Knowledge Base
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  Download
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  Product Flyer
                </a>
              </li>
            </ul>
          </div>

          {/* Support */}
          <div className="text-center">
            <h4 className="text-lg font-semibold text-white mb-6">Support</h4>
            <ul className="space-y-3">
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  Email Support
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  Support Center
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  Documentation
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  FAQ
                </a>
              </li>
            </ul>
          </div>

          {/* Legal */}
          <div className="text-center">
            <h4 className="text-lg font-semibold text-white mb-6">Legal</h4>
            <ul className="space-y-3">
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  Privacy Policy
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  Terms of Service
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  Refund Policy
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="text-white/70 hover:text-white transition-colors flex items-center justify-center group"
                >
                  <ExternalLink className="w-3 h-3 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                  License
                </a>
              </li>
            </ul>
          </div>
        </div>

        {/* Contact Information */}
        <div className="text-center mb-12">
          <h4 className="text-lg font-semibold text-white mb-6">Contact Information</h4>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-6">
            <div className="flex items-center text-white/70">
              <Mail className="w-5 h-5 mr-3" />
              <span>rescuepcrepair@yahoo.com</span>
            </div>
            <div className="flex items-center text-white/70">
              <Phone className="w-5 h-5 mr-3" />
              <span>24/7 Support Available</span>
            </div>
            <div className="flex items-center text-white/70">
              <Globe className="w-5 h-5 mr-3" />
              <span>Worldwide Service</span>
            </div>
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="pt-8 border-t border-gray-700">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="mb-4 md:mb-0 text-center md:text-left">
              <p className="text-white/80 text-sm">
                © 2024 RescuePC Repairs. All rights reserved.
              </p>
              <p className="text-white/60 text-xs mt-1">Built for Windows users worldwide</p>
            </div>
            <div className="flex items-center space-x-4">
              <div className="flex items-center text-white/60">
                <Heart className="w-4 h-4 mr-2 text-red-400" />
                <span className="text-sm">Made with ❤️ for PC users</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

// rescuepc-angular/apps/frontend/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

interface FooterLink {
  name: string;
  href: string;
}

interface FooterSection {
  title: string;
  links: FooterLink[];
}

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent {
  footerSections: FooterSection[] = [
    {
      title: 'Product',
      links: [
        { name: 'Features', href: '#features' },
        { name: 'Pricing', href: '#pricing' },
        { name: 'Knowledge Base', href: '#knowledge-base' },
        { name: 'Download', href: '#download' },
        { name: 'Product Flyer', href: '#flyer' }
      ]
    },
    {
      title: 'Support',
      links: [
        { name: 'Email Support', href: 'mailto:rescuepcrepair@yahoo.com' },
        { name: 'Support Center', href: '#support' },
        { name: 'Documentation', href: '#docs' },
        { name: 'FAQ', href: '#faq' }
      ]
    },
    {
      title: 'Legal',
      links: [
        { name: 'Privacy Policy', href: '#privacy' },
        { name: 'Terms of Service', href: '#terms' },
        { name: 'Refund Policy', href: '#refund' },
        { name: 'License', href: '#license' }
      ]
    }
  ];

  contactInfo = [
    { icon: '📧', text: 'rescuepcrepair@yahoo.com' },
    { icon: '📞', text: '24/7 Support Available' },
    { icon: '🌐', text: 'Worldwide Service' }
  ];

  scrollToSection(href: string): void {
    if (href.startsWith('#')) {
      const element = document.querySelector(href);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
      }
    }
  }
} 
<footer class="footer py-16 relative overflow-hidden">
  <!-- Background Elements -->
  <div class="absolute inset-0 bg-gradient-to-br from-gray-900/50 via-black/50 to-gray-900/50"></div>
  <div class="absolute top-0 left-0 w-96 h-96 bg-blue-500/5 rounded-full blur-3xl"></div>
  <div class="absolute bottom-0 right-0 w-80 h-80 bg-purple-500/5 rounded-full blur-3xl"></div>

  <div class="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
    <!-- Main Footer Content -->
    <div class="text-center mb-12">
      <!-- Company Info -->
      <div class="flex items-center justify-center mb-8">
        <div class="w-16 h-16 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center mr-4">
          <span class="text-2xl text-white">🛡️</span>
        </div>
        <h3 class="text-3xl font-bold text-white">RescuePC Repairs</h3>
      </div>

      <p class="text-white/80 mb-8 leading-relaxed max-w-2xl mx-auto text-lg">
        Professional Windows repair toolkit with military-grade security. Lifetime license, 24/7
        support, and offline operation for maximum privacy and performance.
      </p>

      <div class="flex items-center justify-center space-x-8 mb-8">
        <div class="flex items-center text-white/60">
          <span class="text-lg mr-2">📧</span>
          <span class="text-sm">rescuepcrepair@yahoo.com</span>
        </div>
        <div class="flex items-center text-white/60">
          <span class="text-lg mr-2">⏰</span>
          <span class="text-sm">24/7 Support</span>
        </div>
      </div>
    </div>

    <!-- Navigation Links -->
    <div class="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
      <div
        *ngFor="let section of footerSections"
        class="text-center"
      >
        <h4 class="text-lg font-semibold text-white mb-6">{{ section.title }}</h4>
        <ul class="space-y-3">
          <li
            *ngFor="let link of section.links"
          >
            <a
              [href]="link.href"
              (click)="scrollToSection(link.href); $event.preventDefault()"
              class="text-white/70 hover:text-white transition-colors flex items-center justify-center group cursor-pointer"
            >
              <span class="text-xs mr-2 opacity-0 group-hover:opacity-100 transition-opacity">🔗</span>
              {{ link.name }}
            </a>
          </li>
        </ul>
      </div>
    </div>

    <!-- Contact Information -->
    <div class="text-center mb-12">
      <h4 class="text-lg font-semibold text-white mb-6">Contact Information</h4>
      <div class="flex flex-col sm:flex-row items-center justify-center gap-6">
        <div
          *ngFor="let contact of contactInfo"
          class="flex items-center text-white/70"
        >
          <span class="text-lg mr-3">{{ contact.icon }}</span>
          <span>{{ contact.text }}</span>
        </div>
      </div>
    </div>

    <!-- Bottom Bar -->
    <div class="pt-8 border-t border-gray-700">
      <div class="flex flex-col md:flex-row justify-between items-center">
        <div class="mb-4 md:mb-0 text-center md:text-left">
          <p class="text-white/80 text-sm">
            © 2024 RescuePC Repairs. All rights reserved.
          </p>
          <p class="text-white/60 text-xs mt-1">Built for Windows users worldwide</p>
        </div>
        <div class="flex items-center space-x-4">
          <div class="flex items-center text-white/60">
            <span class="text-lg mr-2 text-red-400">❤️</span>
            <span class="text-sm">Made with ❤️ for PC users</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
